export const FETCH_CARS = "FETCH_CARS";
export const FETCH_CARS_SUCCESS = "FETCH CARS SUCCESS";
export const FETCH_CARS_FAIL = "FETCH CATS FAIL";

export const FETCH_SINGLE_CAR = "FETCH SINGLE CAR";
export const FETCH_SINGLE_CAR_SUCCESS = "FETCH SINGLE CAR SUCCESS";
export const FETCH_SINGLE_CAR_FAIL = "FETCH SINGLE CAR FAIL";

export const ADD_NEW_CAR = "ADD NEW CAR";
export const ADD_NEW_CAR_SUCCESS = "ADD NEW CAR SUCCESS";
export const ADD_NEW_CAR_FAIL = "ADD NEW CAR FAIL";

export const DELETE_CAR = "DELETE CAR";
export const DELETE_CAR_REQUEST = "DELETE CAR REQUEST";
export const DELETE_CAR_SUCCESS = "DELETE CAR SUCCESS";
export const DELETE_CAR_FAIL = "DELETE CAR FAI"

export const REDIRECT_FROM_PAGE = "REDIRECT FROM PAGE";